### ISSUE TITLE
where is pouchDB added

### ISSUE THREAD

**Issue by niklasp** [colinjlacy/offline-ionic-2#1]
I looked through your code but there is no pouchDB integration anywhere. Help me find it or change description as it is missleading.

**Comment by colinjlacy** [comment]
Sorry, you are entirely correct. I never finished this project. I'll change the description like you suggested.

**Comment by colinjlacy** [comment]
BTW, you can see where I left off with PouchDB in the `pouch` branch that I posted while trying to work out problems with the Sync Gateway folks: https://github.com/colinjlacy/offline-ionic-2/tree/pouch
